### PR TITLE
Update to jcb-gdas marine obs yamls

### LINKED ISSUE #1316: Update the obs yaml in jcb-gdas
diff the all the obs space yaml with the ones in this repository and make the necessary changes.

Once done, erase all the obs yamls in the gdasapp ...

### PR DESCRIPTION
**Pull request by JohnSteffen-NOAA**
This PR updates the marine observations yamls introduced in [https://github.com/NOAA-EMC/jcb-gdas/commit/41ee2a276e2688d19eef7d3dcb9567e3042f6843](url) by modifying the observation errors and additional filters to be consistent with the marine candidate experiment. 

It addresses this GDASApp issue [https://github.com/NOAA-EMC/GDASApp/issues/1316](url).

Additionally, yamls for new sea ice retrievals and SMAP/SMOS retrievals are included. 

Close https://github.com/NOAA-EMC/GDASApp/issues/1316

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Thanks @JohnSteffen-NOAA , can you resolve the conflict (argo yaml)? Just ignore what ever I did to the argo yaml and use your filters. I was just making stuff work!

**Comment by JohnSteffen-NOAA** [comment]
Conflict resolved

**Comment by guillaumevernieres** [comment]
Looks fine to me, did you test some of these yamls @JohnSteffen-NOAA ?

**Comment by JohnSteffen-NOAA** [comment]
No, they have not been tested from the jcb-gdas side, only from the parm/soca/obs/config @guillaumevernieres

**Review by danholdaway — APPROVED** [review]

**Review by apchoiCMD — APPROVED** [review]
Look good-

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
Let's not merge this just yet, I don't think these yamls will work with the prep obs task. Were you able to test @JohnSteffen-NOAA ?

**Comment by JohnSteffen-NOAA** [comment]
I'm building the ctests now @guillaumevernieres . I'll update when I get to the prep obs task.

**Comment by AndrewEichmann-NOAA** [comment]
@JohnSteffen-NOAA Do you know where these are to be read in? Like from `obs_list.yaml`? In part I'm curious about the role of the lines
```
- obs space:
    name: {{observation_from_jcb}}
```
since the obs space name is how the file itself, at least the ones under `parm/soca/obs/config`, are found.

**Comment by guillaumevernieres** [comment]
@JohnSteffen-NOAA , I tested some of the obs yamls, no complaints so I'm going to merge this. However, there are a few places in our scripts that still rely in the old obs yamls ... We'll need to fix this at some point.

**Review by guillaumevernieres — APPROVED** [review]

**Comment by guillaumevernieres** [comment]
> @JohnSteffen-NOAA Do you know where these are to be read in? Like from `obs_list.yaml`? In part I'm curious about the role of the lines
> 
> ```
> - obs space:
>     name: {{observation_from_jcb}}
> ```
> 
> since the obs space name is how the file itself, at least the ones under `parm/soca/obs/config`, are found.

it's coming from a processed version of obs_list @AndrewEichmann-NOAA . We have to revisit that part of the code ...

**Comment by guillaumevernieres** [comment]
The ci error seems unrelated to your work @JohnSteffen-NOAA . 
@danholdaway , I'm going to ignore the failure, unless you think the issue is in this pr.

**Comment by danholdaway** [comment]
@guillaumevernieres the testing issue is fixed now.

**Pull request merged**
