### PR TITLE
Yaml updates for use with updated GDASApp submodules

### LINKED ISSUE #6: Update yamls to work with updated GDASApp JEDI submodules
GDASApp issue [#1117](https://github.com/NOAA-EMC/GDASApp/issues/1117) documents the updating of JEDI submodules in GDASApp `sorc`.  The updated JEDI submodules require changes to the following jcb-gdas yamls
- `model/atmosphere/background_error_hybrid_gsibec_bump.yaml.j2`
- `model/atmosphere/background_error_static_gsibec.yaml.j2`
- `observations/atmosphere-lgetkf/amsua_n19.yaml.j2`
- `observations/atmosphere/amsua_n19.yaml.j2`

The string `gsi covariance` is changed to `gsi static covariance` in the background error yamls.  The [names](https://github.com/NOAA-EMC/GDASApp/issues/1117#issuecomment-2120546792) of several bias correction variables are changed in the amsua_n19 yamls.

This issue is opened to document these changes to jcb-gdas.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
GDASApp PR [#1123](https://github.com/NOAA-EMC/GDASApp/pull/1123) updates the hashes for select JEDI repositories.  The updated hashes require yaml updates.
 - add `static` keyword to `gsi covariance`
 - update names used for radiance bias correction terms
 
Resolves #6

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
**NOTE** This PR is opened as a draft since merger of the changes in this PR into jcb-gdas `develop` needs to be coordinated with GDASApp PR [#1123](https://github.com/NOAA-EMC/GDASApp/pull/1123).

**Comment by RussTreadon-NOAA** [comment]
Moving forward with GDASApp PR [#1123](https://github.com/NOAA-EMC/GDASApp/pull/1123).  Therefore, mark this PR as _Ready for review_

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA & @danholdaway , merger of this PR into jcb-gdas `develop` is required to fully close out GDASApp PR [#1123](https://github.com/NOAA-EMC/GDASApp/pull/1123).  

Once this PR is in `develop`, I will update the jcb-gdas hash in PR [#1123](https://github.com/NOAA-EMC/GDASApp/pull/1123).

**Review by CoryMartin-NOAA — APPROVED** [review]
Changes look good and necessary for the new bias correction predictor names

**Pull request merged**
