### PR TITLE
replace fixed distribution name with templated variable

### LINKED ISSUE #22: Update jcb templates for local ensemble observer and solver jobs
g-w issue [#2415](https://github.com/NOAA-EMC/global-workflow/issues/2415) adds jedi local ensemble observer and solver jobs. Changes are required in jcb-gdas lgetkf templates to support this new functionality. This issue is opened to document changes to jcb templates.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
The lgetkf observer and solver steps use different distribution types.  Observer runs use `RoundRobin`.  Solver runs use `Halo`.  This PR replaces the currently fixed distribution type, `Halo`, in `observations/atmosphere-lgetkf/` templates with variable `distribution_type`.  This allows the distribution type to be set at runtime.
 
Resolves #22

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@TravisElless-NOAA and @SamuelDegelia-NOAA , this PR replaces the hardwired `Halo` distribution
```
    distribution:
      name: Halo
```
with a templated variable `distribution_type`
```
    distribution:
      name: "{{distribution_type}}"
```
This change is made to all templates in `observations/atmosphere-lgetkf/`.  With this change we can externally toggle between `RoundRobin` for the lgetkf observer and `Halo` for the lgetkf solver. This PR has been tested as part of g-w PR [#2833](https://github.com/NOAA-EMC/global-workflow/pull/2833) and GDASApp PR [#1252](https://github.com/NOAA-EMC/GDASApp/pull/1252).

If either of you have time, can you review these changes?

**Review by SamuelDegelia-NOAA — APPROVED** [review]
Great idea @RussTreadon-NOAA, looks good to me!

**Comment by RussTreadon-NOAA** [comment]
Thanks @SamuelDegelia-NOAA for the review and approval!

**Review by TravisElless-NOAA — APPROVED** [review]
Thanks for adding this flexibility @RussTreadon-NOAA

**Pull request merged**
