### PR TITLE
Update observation yamls for atmosphere var and local ensemble DA

### LINKED ISSUE #20: Update observation templates
GDASApp issue [#1227](https://github.com/NOAA-EMC/GDASApp/issues/1227) requires changes to several observation templates.  These changes include
 - updating radiance bias correction keywords
 - renaming templates to match bufr2ioda converter names
 - adding observation templates for lgetkf

Work for this issue will be done in [RussTreadon-NOAA:feature/bufr2ioda](https://github.com/RussTreadon-NOAA/jcb-gdas/tree/feature/bufr2ioda).

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
This PR updates observation templates use by the variational and local ensemble atmosphere applications.  The following changes are included in this PR
- updating radiance bias correction keywords
- renaming templates to match bufr2ioda converter names
- adding observation templates for lgetkf

Resolves #20

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , the changes in this PR are ready for review. Who among our UFO validation staff do you recommend as reviewers?

@CoryMartin-NOAA , I think the automated testing failed because it is looking for `feature/bufr2ioda` in the NOAA-EMC/jcb-gdas repo.  This branch does not exist in NOAA-EMC/jcb-gdas.   Branch `feature/bufr2ioda` is in my jcb-gdas fork.  Can/should we generalize automated testing to clone the PR branch from the appropriate repo?

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I'm not sure if it's easy to use the forks for the automated testing. Dan set this up so I'm not sure how it works, but we can look into it

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA I'm not sure if it's easy to use the forks for the automated testing. Dan set this up so I'm not sure how it works, but we can look into it

Thank you @CoryMartin-NOAA .  If we want to explore this possibility, it can be done via a different issue & PR

**Comment by CoryMartin-NOAA** [comment]
if the test failure causes a problem with merging we can always force-merge, we have the power (but we must use that power judiciously)

**Review by ADCollard — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Thank you @ADCollard and @CoryMartin-NOAA

**Pull request merged**
